### ISSUE TITLE
Continuous integration meta-issue

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#249]
Set up, or try to set up, CI on/with/in:
- [x] MinGW
- [ ] MSVC (related: https://github.com/ocsigen/lwt/issues/205)
- [ ] js_of_ocaml
- [ ] BuckleScript
- [ ] Mirage
- [x] Test with libev on Cygwin.
- [ ] Run fuse in one of the Linux matrix rows to force blocking of filesystem calls.
  
  > Perhaps something analogous can be done for Windows. Anyway, many of the Windows calls are currently implemented by forwarding to `Unix`, which blocks the whole process.
- [ ] Coverage analysis for writing more tests.

Linux (Ubuntu), OS X, Cygwin already covered: https://github.com/ocsigen/lwt/pull/240 https://github.com/ocsigen/lwt/pull/246

**Comment by michipili** [comment]
I will have a look at the `js_of_ocaml` point.

**Comment by aantron** [comment]
Further progress will be made as side-effects of other issues, so closing this now.
