### ISSUE TITLE
[easy] Fix whitespace, formatting, prettify the code

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#393]
When code doesn't look good, it is difficult to read and understand. We want Lwt to be easy to work on.

Basically, if you run into any strange indentation, please go ahead and fix it :) Here are some ~~immediate~~ examples from the recent past: [[~~1~~](https://github.com/ocsigen/lwt/blob/1eb217a6ac9bf86d522e5e31c1d1a10f53e59df3/src/unix/lwt_io.ml#L1044-L1050)] [[~~2~~](https://github.com/ocsigen/lwt/blob/1eb217a6ac9bf86d522e5e31c1d1a10f53e59df3/src/unix/lwt_io.ml#L1279-L1281)] [[~~3~~](https://github.com/ocsigen/lwt/blob/1eb217a6ac9bf86d522e5e31c1d1a10f53e59df3/src/unix/lwt_unix.cppo.mli#L75-L79)] [[~~4~~](https://github.com/ocsigen/lwt/blob/1eb217a6ac9bf86d522e5e31c1d1a10f53e59df3/src/unix/lwt_unix.cppo.ml#L484)].

It's recommended not to do this to a file that has an [open, recent pull request](https://github.com/ocsigen/lwt/pulls), to avoid a merge conflict. "Recent" is probably less than a couple months old. Also, check any [in-progress](https://github.com/ocsigen/lwt/labels/in%20progress) or [easy](https://github.com/ocsigen/lwt/labels/easy) issues for an idea of what is being worked on. On the other hand, don't worry too much – in case of a bad conflict, maintainers exist to make sure nobody has to do too much merging work :)

In particular, at the moment, `lwt.ml` (#354) probably shouldn't be touched, although you can edit the *new* one's whitespace by opening pull requests against the `wat` branch that #354 comes from.

Some pointers:

- Lwt uses 80-column lines. Comment lines should use up as much of that as possible.
- Two-space tabs (tabs as spaces!).
- I obviously prefer the formatting as in #354 ([example](https://github.com/ocsigen/lwt/blob/fdff5c09d47d2b020d4998ebed922acf383a2e9d/src/core/lwt.ml#L1710)), but any improvement is welcome.
- ~~If you know how to use [ocp-indent](https://github.com/OCamlPro/ocp-indent), teach us/me, or tell what it's capable of :)~~ Thanks @Richard-Degenne, @vasilisp!
- If you want to discuss what the whitespace *should* be, please go ahead!

<br/>

This is an ongoing issue. Known to be in progress or done:

- [x] ocp-indent applied to `lwt_stream.ml` (#400, @Richard-Degenne).
- [x] ocp-indent applied to the rest of the OCaml files (#409, @Richard-Degenne).
- [x] clang-format applied to C files (#416, @Richard-Degenne).

**Comment by Richard-Degenne** [comment]
One way to enforce sensible indentation throughout the whole codebase would be to add a `.ocp-indent` file to the project. That also means that if a developer has ocp-indent installed in their editor, it will automatically follow the same indentation rules when editing / writing code.

I'll try to format some files with the default settings, just to see how it looks.

**Comment by vasilisp** [comment]
We have the following `.ocp-indent` in most Ocsigen repos:

```
normal
with=0
syntax=lwt mll
max_indent=2
```

I am surprised that there isn't one in Lwt already. I don't know how much our configuration differs from the default, but its results are in line with the established OCaml style.

**Comment by Richard-Degenne** [comment]
Yes, these are also my default settings (used when I don't have a `.ocp-indent` inside the project).

If this is standard inside Ocsigen projects, I can go ahead and add it, then start "normalizing" existing files to match these settings.

**Comment by aantron** [comment]
That sounds reasonable. How about converting one file first, say something large like `lwt_unix.ml`? That should give a good idea of what the settings will do. I'm scared of applying it to the whole codebase right away :)

Also, is it still easy to separate history into whitespace-only and logic-changing commits when using ocp-indent in a text editor? Or does it encourage conflating the two by making whitespace changes too eagerly?

**Comment by aantron** [comment]
Scratch that, `lwt_stream.ml` instead of `lwt_unix.ml`. I think that is the least likely to cause conflicts with anyone's work.

**Comment by Richard-Degenne** [comment]
> Also, is it still easy to separate history into whitespace-only and logic-changing commits when using ocp-indent in a text editor? Or does it encourage conflating the two by making whitespace changes too eagerly?

Well, this is entirely up to you, and the way you use your editor; ocp-indent is only here to help the editor auto-indenting the code.

In Vim, for example, you can
- Have a new line correctly indented after you hit Return;
- Type `==` to auto-indent the current line;
- Auto-indent any block of lines you want with the Visual mode;
- Auto-indent the whole file with `gg=G`.

I don't know much about Emacs and VSCode, but I'm sure they have similar features.

**Comment by aantron** [comment]
Ok, that sounds good :)

**Comment by Richard-Degenne** [comment]
I've pushed [a first commit](https://github.com/Richard-Degenne/lwt/commit/5c1e501245f7e2bc324fe319032997e7647cde60) where I've indented `lwt_stream.ml` and its `mli` using the settings given by @vasilisp. It looks ok. There is one thing bothering me, though: the lack of indentation after a match clause makes it difficult to discern the block and the following match clause ([example](https://github.com/Richard-Degenne/lwt/blob/5c1e501245f7e2bc324fe319032997e7647cde60/src/core/lwt_stream.ml#L369-L380)).

There is an option in ocp-indent to change that, just tell me what you think.

Also, is it too early to open a PR, or should I open one and mark it as a WIP for the time being?

**Comment by aantron** [comment]
It looks pretty good, actually. The only thing I'd say ocp-indent got wrong is the deprecation annotations (`[@@ocaml.deprecated]`), but maybe we can survive that. If it's not configurable, maybe we can PR to ocp-indent in the future. Or maybe I'm wrong, and ocp-indent is right :)

For the match cases, I eventually agreed with indenting like ocp-indent does. I've taken to inserting blank lines when that makes the next match case difficult to find. We can insert them manually later (or now), in a hand-crafted prettification pass :)

If you want to go through the whole file and make it beautiful, go ahead :) But I think this is already helpful, and worth a PR on its own.

**Comment by aantron** [comment]
Thanks for the change. If willing to do more, I think basically the only files currently being worked on are `src/core/lwt.ml` and `src/unix/lwt_unix.cppo,ml[i]`. Everything else is fair game for ocp-indent. Might be too tedious, though :)

**Comment by Richard-Degenne** [comment]
About the C files, there is `clang-format`, which natively support Google-style formatting.

I'll give it a shot later today.
