### ISSUE TITLE
[easy] Involved tests for Lwt_list

### ISSUE THREAD

**Issue by aantron** [ocsigen/lwt#395]
For each (pair of) function(s) in [`Lwt_list`](https://ocsigen.org/lwt/dev/api/Lwt_list), (say `Lwt_list.map_s` and `Lwt_list.map_p`) we should probably test:

- [x] ~~How they respond to exceptions raised by `f`, i.e. `Lwt_list.map_s (fun _ -> raise Exit) ...`~~ (@jsthomas in #512). The `_p` functions might be particularly interesting here. We should find out what they actually do, and document it (or document `Lwt_list` at all, for that matter).
- [x] ~~That the `_s` functions really run `f` in series, and the `_p` functions really run it in parallel. The parallel tests should be easier here, as one could `Lwt.wakeup_later` a promise that another invocation of `f` is waiting on, and verify that the other invocation does some work first, i.e. two or more invocations "talk" to each other. Not immediately sure what to do for `_s`.~~ (@jsthomas in #535).
- [x] After #347 is addressed, we should test that all functions are stack-safe, by running them on big lists.

See #385 for the testing workflow.

**Comment by jsthomas** [comment]
I'm interested in working on this issue.

**Comment by aantron** [comment]
For the `_p` functions, it looks like the ones that depend on `Lwt.join` (`iter_p` and `iteri_p`), if multiple calls to `f` fail, the failure of the first one to fail in time will be reported. For all other `_p` functions, it looks like the left-most failure will be reported, regardless of whether that was the first failure in time.

That may be worth fixing.

It's probably best to wait until we are testing for tail-recursive implementations, as we may find some stack bugs that we have to fix, and that will affect how we may want to fix exception reporting.

**Comment by aantron** [comment]
I think there is also a difference in *when* the promises returned by the `_p` functions are resolved. For the ones that internally use `join`, the final promises are resolved only when all the individual promises created for the whole list resolve. For the rest, if one of the individual promises is rejected, the final promise is rejected right away, without waiting for any promises further down the list to be resolved.

We should probably choose what's right, and test for these behaviors. I suspect that `join`-like behavior is the most desirable. It most closely mimics the behavior of the `_p` functions in the case where none of the promises are rejected.

**Comment by aantron** [comment]
Also, I find the `Lwt_list` tests to be pretty difficult to read for what they are. If you feel this way as well, you're welcome to refactor/simplify them. I usually prefer for test cases to be as self-contained and immediately legible as possible, and all those weird helpers in `Lwt_list` defeat that.

**Comment by aantron** [comment]
Resolved by #531, #535, #538, thanks @jsthomas!

There is still the matter of documenting how `Lwt_list` functions respond to promise rejection (e.g., if multiple promises are rejected, which rejection is propagated to the final promise, etc). However, we can deal with that when documenting `Lwt_list`.
